-- ============================================================================
-- SCRIPT SQL DE CREATION DE LA BASE DE DONNEES - SGA LOT 1
-- ============================================================================

-- Suppression des triggers et de la vue
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW VUE_ACCES_DETAIL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Suppression des tables existantes (ordre respectant les clés étrangères)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HISTORIQUE_EVENEMENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DROIT_ACCES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ACCES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TYPE_ACCES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BADGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LIEU'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERSONNE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROFIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================================
-- 1. CREATION DES TABLES
-- ============================================================================

-- Table PROFIL
CREATE TABLE PROFIL 
(
    id_profil       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    libelle_profil  VARCHAR2(50) NOT NULL,
    description     VARCHAR2(255),
    CONSTRAINT      pk_profil PRIMARY KEY (id_profil),
    CONSTRAINT      uq_libelle_profil UNIQUE (libelle_profil)
);

-- Table PERSONNE (Enrichie pour l'authentification)
CREATE TABLE PERSONNE 
(
    id_personne     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nom             VARCHAR2(100) NOT NULL,
    prenom          VARCHAR2(100) NOT NULL,
    fonction        VARCHAR2(100),
    login           VARCHAR2(50),
    mot_de_passe    VARCHAR2(64), -- Stockage du hash SHA-256 (64 caractères hex)
    statut          VARCHAR2(20) DEFAULT 'ACTIF' NOT NULL,
    id_profil       NUMBER,
    CONSTRAINT      pk_personne PRIMARY KEY (id_personne),
    CONSTRAINT      fk_personne_id_profil FOREIGN KEY (id_profil) REFERENCES PROFIL(id_profil),
    CONSTRAINT      chk_personne_statut CHECK (statut IN ('ACTIF', 'INACTIF')),
    CONSTRAINT      uq_personne_login UNIQUE (login)
);

-- Table LIEU
CREATE TABLE LIEU 
(
    id_lieu         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    libelle_lieu    VARCHAR2(100) NOT NULL,
    emplacement     VARCHAR2(150) NOT NULL,
    capacite_max    NUMBER(4) DEFAULT 1 NOT NULL,
    statut          VARCHAR2(20) DEFAULT 'OUVERT' NOT NULL,
    CONSTRAINT      pk_lieu PRIMARY KEY (id_lieu),
    CONSTRAINT      chk_lieu_statut CHECK (statut IN ('OUVERT', 'FERME', 'BLOQUE'))
);

-- Table BADGE
CREATE TABLE BADGE 
(
    num_badge       VARCHAR2(50) NOT NULL,
    date_emission   DATE DEFAULT SYSDATE NOT NULL,
    date_expiration DATE NOT NULL,
    statut          VARCHAR2(20) DEFAULT 'ACTIF' NOT NULL,
    id_personne     NUMBER NOT NULL,
    id_lieu         NUMBER NOT NULL,
    CONSTRAINT      pk_badge PRIMARY KEY (num_badge),
    CONSTRAINT      fk_badge_id_personne FOREIGN KEY (id_personne) REFERENCES PERSONNE(id_personne),
    CONSTRAINT      fk_badge_id_lieu FOREIGN KEY (id_lieu) REFERENCES LIEU(id_lieu) ON DELETE CASCADE,
    CONSTRAINT      chk_badge_statut CHECK (statut IN ('ACTIF', 'SUSPENDU', 'EXPIRE', 'REVOQUE')),
    CONSTRAINT      chk_badge_dates CHECK (date_expiration > date_emission)
);

-- Table TYPE_ACCES (Spécifique Lot 1)
CREATE TABLE TYPE_ACCES 
(
    id_type_acces   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    libelle         VARCHAR2(100) NOT NULL,
    description     VARCHAR2(300),
    statut          CHAR(1) DEFAULT 'A' NOT NULL,
    date_creation   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT      pk_type_acces PRIMARY KEY (id_type_acces),
    CONSTRAINT      uq_type_acces_libelle UNIQUE (libelle),
    CONSTRAINT      chk_type_acces_statut CHECK (statut IN ('A', 'I'))
);

-- Table ACCES (Adaptée Lot 1 avec clé étrangère vers TYPE_ACCES, statut et dates d'audit)
CREATE TABLE ACCES 
(
    id_acces          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    libelle           VARCHAR2(150) NOT NULL,
    description       VARCHAR2(300),
    id_type_acces     NUMBER NOT NULL,
    id_lieu           NUMBER NOT NULL,
    statut            CHAR(1) DEFAULT 'A' NOT NULL,
    date_creation     DATE DEFAULT SYSDATE NOT NULL,
    date_modification DATE,
    CONSTRAINT        pk_acces PRIMARY KEY (id_acces),
    CONSTRAINT        fk_acces_id_type FOREIGN KEY (id_type_acces) REFERENCES TYPE_ACCES(id_type_acces),
    CONSTRAINT        fk_acces_id_lieu FOREIGN KEY (id_lieu) REFERENCES LIEU(id_lieu) ON DELETE CASCADE,
    CONSTRAINT        chk_acces_statut CHECK (statut IN ('A', 'I'))
);

-- Table DROIT_ACCES
CREATE TABLE DROIT_ACCES 
(
    id_droit        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_profil       NUMBER NOT NULL,
    id_lieu         NUMBER NOT NULL,
    jour_semaine    VARCHAR2(15) NOT NULL,
    heure_debut     INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    heure_fin       INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    CONSTRAINT      pk_droit_acces PRIMARY KEY (id_droit),
    CONSTRAINT      fk_droit_id_profil FOREIGN KEY (id_profil) REFERENCES PROFIL(id_profil) ON DELETE CASCADE,
    CONSTRAINT      fk_droit_id_lieu FOREIGN KEY (id_lieu) REFERENCES LIEU(id_lieu) ON DELETE CASCADE,
    CONSTRAINT      chk_jour_semaine CHECK (jour_semaine IN ('LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI', 'DIMANCHE', 'TOUS')),
    CONSTRAINT      chk_heure_valide CHECK (heure_fin > heure_debut)
);

-- Table HISTORIQUE_EVENEMENT
CREATE TABLE HISTORIQUE_EVENEMENT 
(
    id_evenement                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    type_evenement              VARCHAR2(30) NOT NULL,
    date_evenement              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    statut_resultat             VARCHAR2(20) NOT NULL,
    description_justification   VARCHAR2(255) NOT NULL,
    num_badge                   VARCHAR2(50),
    id_acces                    NUMBER,
    id_lieu                     NUMBER,
    id_personne                 NUMBER,
    CONSTRAINT                  pk_historique_evenement PRIMARY KEY (id_evenement),
    CONSTRAINT                  fk_hist_num_badge FOREIGN KEY (num_badge) REFERENCES BADGE(num_badge),
    CONSTRAINT                  fk_hist_id_acces FOREIGN KEY (id_acces) REFERENCES ACCES(id_acces),
    CONSTRAINT                  fk_hist_id_lieu FOREIGN KEY (id_lieu) REFERENCES LIEU(id_lieu),
    CONSTRAINT                  fk_hist_id_personne FOREIGN KEY (id_personne) REFERENCES PERSONNE(id_personne),
    CONSTRAINT                  chk_type_evenement CHECK (type_evenement IN ('ACCES_PHYSIQUE', 'MODIF_BADGE', 'MODIF_LIEU')),
    CONSTRAINT                  chk_statut_resultat CHECK (statut_resultat IN ('ACCORDE', 'REFUSE', 'SUCCES', 'ECHEC'))
);


-- ============================================================================
-- 2. INDEX D'OPTIMISATION DES PERFORMANCES (Cf. Section 7.3 du DSL)
-- ============================================================================
CREATE INDEX IDX_ACCES_TYPE ON ACCES(id_type_acces);
CREATE INDEX IDX_ACCES_LIEU ON ACCES(id_lieu);
CREATE INDEX IDX_ACCES_STATUT ON ACCES(statut);


-- ============================================================================
-- 3. CREATION DES TRIGGERS
-- ============================================================================

-- Trigger de mise à jour automatique de date_modification
CREATE OR REPLACE TRIGGER TRG_ACCES_MODIF
BEFORE UPDATE ON ACCES
FOR EACH ROW
BEGIN
    :NEW.date_modification := SYSDATE;
END;
/

-- Trigger de mise en majuscule systématique pour l'unicité insensible à la casse
CREATE OR REPLACE TRIGGER TRG_TYPE_ACCES_UPPER
BEFORE INSERT OR UPDATE ON TYPE_ACCES
FOR EACH ROW
BEGIN
    :NEW.libelle := UPPER(:NEW.libelle);
END;
/


-- ============================================================================
-- 4. CREATION DE LA VUE DETALLEE DES ACCES (Cf. Section 5.5 du DCP)
-- ============================================================================
CREATE OR REPLACE VIEW VUE_ACCES_DETAIL AS
SELECT 
    a.id_acces, 
    a.libelle, 
    a.description, 
    ta.libelle AS type_acces, 
    l.libelle_lieu AS lieu, 
    a.statut, 
    a.date_creation, 
    a.date_modification
FROM ACCES a 
JOIN TYPE_ACCES ta ON ta.id_type_acces = a.id_type_acces 
JOIN LIEU l ON l.id_lieu = a.id_lieu
WHERE a.statut = 'A';
/


-- ============================================================================
-- 5. JEU DE DONNEES DE TEST MINIMAL REQUIS (Cf. Section 5.6 du DCP)
-- ============================================================================

-- Insertion dans PROFIL
INSERT INTO PROFIL (libelle_profil, description) VALUES ('ADMINISTRATEUR', 'Gestion complète du système et des accès');
INSERT INTO PROFIL (libelle_profil, description) VALUES ('AGENT_SECURITE', 'Consultation et contrôle des accès en temps réel');
INSERT INTO PROFIL (libelle_profil, description) VALUES ('DSI', 'Responsable informatique avec droits de lecture globaux');
INSERT INTO PROFIL (libelle_profil, description) VALUES ('ETUDIANT', 'Accès restreint aux salles de cours et labos');
INSERT INTO PROFIL (libelle_profil, description) VALUES ('ENSEIGNANT', 'Accès aux salles de cours, bureaux et labos');

-- Insertion dans PERSONNE (10 personnes requises, mots de passe hashés en SHA-256)
-- 'admin' avec mot de passe 'admin' -> hash 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
-- 'agent' avec mot de passe 'agent' -> hash 2f28148b11116c49e79435b6a715f5d3cb8b30364d081f9b0b4e5488eb742296
-- 'dsi' avec mot de passe 'dsi'     -> hash fd5a6df48c962b1aa33a595cb2dfa14a0f443cfbf98964d4d12521ab251218df
INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('OUEDRAOGO', 'Askia', 'Admin SGA', 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIF', 1);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('GUIGMA', 'Christophe', 'Garde Poste', 'agent', '2f28148b11116c49e79435b6a715f5d3cb8b30364d081f9b0b4e5488eb742296', 'ACTIF', 2);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('NAGALO', 'Alexis', 'Directeur SI', 'dsi', 'fd5a6df48c962b1aa33a595cb2dfa14a0f443cfbf98964d4d12521ab251218df', 'ACTIF', 3);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('TRAORE', 'Souleymane', 'Étudiant IC1', 'traore.s', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'ACTIF', 4);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('KABORE', 'Fatoumata', 'Étudiante IC1', 'kabore.f', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'ACTIF', 4);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('SOW', 'Ibrahim', 'Enseignant Électricité', 'sow.i', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'ACTIF', 5);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('ZONGO', 'Mariam', 'Secrétaire', 'zongo.m', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'ACTIF', NULL);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('COMPAORE', 'Pierre', 'Technicien', 'compaore.p', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'ACTIF', NULL);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('DIARRA', 'Amadou', 'Agent Sécurité Nuit', 'diarra.a', '2f28148b11116c49e79435b6a715f5d3cb8b30364d081f9b0b4e5488eb742296', 'ACTIF', 2);

INSERT INTO PERSONNE (nom, prenom, fonction, login, mot_de_passe, statut, id_profil) 
VALUES ('SAWADOGO', 'Adama', 'Stagiaire', 'sawadogo.a', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'INACTIF', NULL);

-- Insertion dans LIEU (5 lieux différents requis)
INSERT INTO LIEU (libelle_lieu, emplacement, capacite_max, statut) VALUES ('Salle A101 (Cours)', 'Bâtiment Principal 1er étage', 50, 'OUVERT');
INSERT INTO LIEU (libelle_lieu, emplacement, capacite_max, statut) VALUES ('Labo Réseaux', 'Bloc B RDC', 20, 'OUVERT');
INSERT INTO LIEU (libelle_lieu, emplacement, capacite_max, statut) VALUES ('Parking Nord', 'Extérieur Côté Administratif', 100, 'OUVERT');
INSERT INTO LIEU (libelle_lieu, emplacement, capacite_max, statut) VALUES ('Administration', 'Bâtiment A RDC', 15, 'OUVERT');
INSERT INTO LIEU (libelle_lieu, emplacement, capacite_max, statut) VALUES ('Salle des Serveurs', 'Sous-sol Bloc A', 2, 'OUVERT');

-- Insertion dans TYPE_ACCES (5 types d'accès requis)
INSERT INTO TYPE_ACCES (libelle, description) VALUES ('PORTE', 'Porte battante avec verrouillage magnétique');
INSERT INTO TYPE_ACCES (libelle, description) VALUES ('BARRIERE', 'Barrière levante automatique');
INSERT INTO TYPE_ACCES (libelle, description) VALUES ('PORTILLON', 'Portillon pivotant de sécurité');
INSERT INTO TYPE_ACCES (libelle, description) VALUES ('PARKING', 'Portail d''entrée de parking avec détecteur de boucle');
INSERT INTO TYPE_ACCES (libelle, description) VALUES ('ASCENSEUR', 'Contrôle d''accès par badge dans la cabine d''ascenseur');

-- Insertion dans ACCES (8 points d'accès répartis sur les 5 lieux)
INSERT INTO ACCES (libelle, description, id_type_acces, id_lieu) VALUES ('Porte Principale Entrée A', 'Entrée principale de l''administration', 1, 4);
INSERT INTO ACCES (libelle, description, id_type_acces, id_lieu) VALUES ('Barrière Véhicules Nord', 'Barrière d''accès au parking', 2, 3);
INSERT INTO ACCES (libelle, description, id_type_acces, id_lieu) VALUES ('Portillon Piétons Administration', 'Accès piéton filtré', 3, 4);
INSERT INTO ACCES (libelle, description, id_type_acces, id_lieu) VALUES ('Ascenseur Bâtiment Principal', 'Contrôle cabine ascenseur', 5, 1);
INSERT INTO ACCES (libelle, description, id_type_acces, id_lieu) VALUES ('Porte Labo Réseaux', 'Porte d''accès au labo', 1, 2);
INSERT INTO ACCES (libelle, description, id_type_acces, id_lieu) VALUES ('Porte Blindée Serveurs', 'Sécurité renforcée salle serveurs', 1, 5);
INSERT INTO ACCES (libelle, description, id_type_acces, id_lieu) VALUES ('Portail Sortie Parking', 'Portail de sortie automatique', 4, 3);
INSERT INTO ACCES (libelle, description, id_type_acces, id_lieu) VALUES ('Porte Secours A101', 'Porte de sortie de secours', 1, 1);

-- Insertion dans BADGE (pour tester l'intégrité de la base)
INSERT INTO BADGE (num_badge, date_emission, date_expiration, statut, id_personne, id_lieu)
VALUES ('B-1001', SYSDATE, SYSDATE + 365, 'ACTIF', 1, 4);
INSERT INTO BADGE (num_badge, date_emission, date_expiration, statut, id_personne, id_lieu)
VALUES ('B-1002', SYSDATE, SYSDATE + 365, 'ACTIF', 2, 4);
INSERT INTO BADGE (num_badge, date_emission, date_expiration, statut, id_personne, id_lieu)
VALUES ('B-1003', SYSDATE, SYSDATE + 365, 'ACTIF', 3, 5);

COMMIT;
/
